---
global:
  scrape_interval: 5s
  evaluation_interval: 5s

  external_labels:
    monitor: "prometheus"

# Targets to scrape
scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "phoenix-todo-list"
    static_configs:
      - targets: ["localhost:4001"]
