#!/bin/sh

show_help() {
  echo "This script restores a pg_dump backup. It must be run inside the container.

The first positional argument must be the filename of the backup you want to restore:
  - The file must be located in the same directory as this script.
  - DO NOT pass in the full path to the file. Just the filename.
    - e.g. 'phoenix-todo-list--pg-dump-2022-11-01-08-57-30.dump'"
}

if [ "$1" = "--help" ]; then
  show_help
  exit
elif [ "$1" = "" ]; then
  show_help
  exit 2
fi

# change to backup directory
cd /var/lib/postgresql/backups/ || exit 1

# restore backup
pg_restore -h localhost -p 5432 -U "$POSTGRES_USER" -d "$POSTGRES_DB" "$1" --clean
