---
version: "3.8"

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: "${PROJECT_NAME}_dev"
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    networks:
      - generic
    ports:
      - "5432:5432"
    volumes:
      - ./volumes/postgres:/var/lib/postgresql/data

networks:
  generic:
    name: generic
    external: true
