---
version: "3.8"

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: todo_list
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    network_mode: host
    volumes:
      - "./support/docker/volumes/postgres:/var/lib/postgresql/data"
  phoenix:
    image: arcanemachine/phoenix-todo-list
    restart: always
    depends_on:
      - db
    env_file:
      - .env.override
    network_mode: host
