---
services:
  postgres:
    hostname: "postgres"
    networks:
      - "phoenix-todo-list"
    ports:
      - "${POSTGRES_PORT:-5432}"

networks:
  traefik-global-proxy:
    external: true
  phoenix-todo-list:
