---
services:
  phoenix:
    environment:
      DATABASE_URL: "${DATABASE_URL:?}"
    networks:
      - "traefik-global-proxy"
      # - "postgres" # this network is only needed if using an postgres container outside of this compose service
    ports:
      - "${PORT:?}"
    labels:
      # enable gzip compression
      - "traefik.http.middlewares.phoenix-todo-list--compress.compress=true"
      - "traefik.http.routers.phoenix-todo-list.middlewares=phoenix-todo-list--compress"

networks:
  traefik-global-proxy:
    external: true
# postgres: # this network is only needed if using an postgres container outside of this compose service
#   external: true
