---
services:
  postgres:
    networks:
      - "phoenix-todo-list"
    ports:
      - "5432"

networks:
  traefik-global-proxy:
    external: true
  # the 'phoenix-todo-list' network is only used when running phoenix and
  # postgres as part of the same container orchestration service
  phoenix-todo-list:
