---
services:
  phoenix:
    environment:
      DATABASE_URL: "${DATABASE_URL:?}"
    networks:
      - "traefik-global-proxy"
      - "postgres" # use this if you are running a postgres container outside of this project's compose service
    ports:
      - "${PORT:?}"
    labels:
      # enable gzip compression
      - "traefik.http.middlewares.phoenix-todo-list--compress.compress=true" # define middleware
      - "traefik.http.routers.phoenix-todo-list.middlewares=phoenix-todo-list--compress" # use middleware

networks:
  traefik-global-proxy:
    external: true
  postgres: # use this if you are running a postgres container outside of this project's compose service
    external: true
