---
services:
  phoenix:
    environment:
      DATABASE_URL: "${DATABASE_URL:?}"
    networks:
      - "traefik-global-proxy"
      - "phoenix-todo-list"
    ports:
      - "${PORT:?}"
    labels:
      # enable gzip compression
      - "traefik.http.middlewares.phoenix-todo-list--compress.compress=true"
      - "traefik.http.routers.phoenix-todo-list.middlewares=phoenix-todo-list--compress"

networks:
  traefik-global-proxy:
    external: true
  phoenix-todo-list:
