#!/bin/bash

show_help() {
  echo "This script creates a pg_dump backup. It must be run inside the container.

The backup file will be created in the same directory as this script. It will be created with a timestamp in the filename.
  - e.g. 'phoenix-todo-list--pg-dump-2022-11-05-06-23-37.dump'

This script takes no arguments."
}

if [ "$1" = "--help" ]; then
  show_help
  exit
fi

# change to backup directory
cd /var/lib/postgresql/backups/ || exit 1

# make backup
pg_dump -h localhost -p 5432 -U "$POSTGRES_USER" -F c -b -v -f "phoenix-todo-list--pg-dump-$(date +'%Y-%m-%d-%H-%M-%S').dump" "$POSTGRES_DB"

# # remove all local backups older than 7 days
# find *.dump -type f -mtime +7 | xargs rm -f
