#!/bin/sh

if [ "$1" = "--help" ]; then
  echo "Outputs template whose output can be piped to an environment file.

This script is typically run by the 'dotenv-generate' script.

NOTE: To use this script's default values, any matching environment variables
must first be unset.

Options:
  - By default, this script outputs a '.env' file.
  - By default, this script generates parameters for a local/dev deployment.
    - To generate params for a remote/prod deployment, pass the '--remote' flag
      when calling this script.
  - To generate a '.envrc' template, pass the '--envrc' flag.
    - This prepends 'export ' to each environment variable so the resulting file
      can be easily sourced using a shell script."
  exit
fi

# parse args
while test $# -gt 0; do
  case "$1" in
  --envrc)
    # generate a '.envrc' style template instead of a '.env'
    is_envrc=1
    ;;
  --remote)
    # configure environment for a 'remote' deployment (i.e. uses HTTPS)
    is_remote=1
    ;;
  esac
  shift
done

if [ ! $is_remote ]; then
  # configure defaults for local deployment
  default_phx_host="phoenix-todo-list.localhost"
  default_traefik_host="localhost"
else
  # configure defaults for remote deployment
  default_phx_host="phoenix-todo-list.nicholasmoen.com"
  default_traefik_host="traefik.nicholasmoen.com"
fi

echo "# phoenix
${is_envrc:+"export "}PHX_HOST=\"${PHX_HOST:-$default_phx_host}\"
${is_envrc:+"export "}PORT=\"${PORT:-4000}\"
${is_envrc:+"export "}SECRET_KEY_BASE=\"${SECRET_KEY_BASE:-$(openssl rand -base64 48)}\"

# db
${is_envrc:+"export "}POSTGRES_DB=\"${POSTGRES_DB:-todo_list}\"
${is_envrc:+"export "}POSTGRES_USER=\"${POSTGRES_USER:-postgres}\"
${is_envrc:+"export "}POSTGRES_PASSWORD=\"${POSTGRES_PASSWORD:-postgres}\"
${is_envrc:+"export "}DATABASE_URL=\"${DATABASE_URL:-ecto://postgres:postgres@localhost/todo_list}\"

# # email
# ${is_envrc:+"export "}AWS_REGION=\"${AWS_REGION:-us-east-1}\"
# ${is_envrc:+"export "}AWS_ACCESS_KEY=\"${AWS_ACCESS_KEY:-your_aws_access_key}\"
# ${is_envrc:+"export "}AWS_SECRET=\"${AWS_SECRET:-your_aws_secret}\"

# docker
${is_envrc:+"export "}IMAGE_TAG=\"${IMAGE_TAG:-$(uname -m)}\"

# traefik
${is_envrc:+"export "}TRAEFIK_HOST=\"${TRAEFIK_HOST:-$default_traefik_host}\""
