#!/usr/bin/env bash

if [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
  echo "This script manages a Compose service for Phoenix + Postgres.

The first positional argument must specify the 'docker-compose' command(s) to run.
  - Examples: up, down, restart, etc.

To use Podman instead of Docker, pass the '--podman' flag as the last positional argument."
  exit
fi

# navigate to containers directory
project_root_directory="$(dirname "$0")/../../.."
containers_directory="$project_root_directory/support/containers"
cd "$containers_directory" || exit 1

# ensure first positional argument is present
if [ "$1" = "" ]; then
  echo "The first positional argument must specify the 'docker-compose' command(s) to run. Examples: up, down, restart, etc.

To use Podman instead of Docker, pass the '--podman' flag as the last positional argument."
  exit 1
else
  # move the first arg into a variable and shift it out of args
  action=$1
  shift
fi

# get last arg
for last_arg; do true; done

# determine which container manager to use ('docker compose' or podman-compose)
application_to_run="docker compose"

if [ "$last_arg" = "--podman" ]; then
  # use podman-compose instead of docker
  application_to_run="podman-compose"

  # remove last arg
  set -- "${@:1:$(($# - 1))}"
fi

# run container action
# shellcheck disable=SC2068,SC2086
$application_to_run -f compose.phoenix.yaml -f networks/compose.phoenix-host.yaml -f compose.phoenix-postgres.yaml -f compose.postgres.yaml -f networks/compose.postgres-host.yaml $action $@
