#!/bin/sh

if [ "$1" = "--help" ]; then
  echo "Copy this project's Caddyfile to the Caddy config directory, then validate the config and restart Caddy.

This script accepts a single positional argument that will specify the Caddyfile to use.
  - Must be one of: local, staging, remote
    - Local: Uses 'localhost' subdomain
    - Remote: Uses real domain name
    - Staging: Like remote, but uses Let's Encrypt testing certificates (to avoid rate limits)"
  exit 0
fi

# navigate to project root directory
cd "$(dirname "$0")/../../" || exit 1

# use remote caddyfile by default
if [ "$1" = "local" ] || [ "$1" = "staging" ] || [ "$1" = "prod" ]; then
  echo "Using '$1' Caddyfile..."
  caddyfile_to_use="Caddyfile.$1"
elif [ "$1" = "local" ]; then
  echo "Using '$1' Caddyfile..."
  caddyfile_to_use="Caddyfile.$1"
else
  echo "First positional argument must be one of: local, staging, prod"
  echo "Aborting..."
  exit 1
fi

caddyfile_config_dir="/etc/caddy"

# copy the caddyfile to the caddy config directory
if ! sudo cp "support/deployment/$caddyfile_to_use" "$caddyfile_config_dir/Caddyfile"; then
  echo "Could not copy the Caddyfile to '$caddyfile_config_dir'. Is Caddy installed?"
  exit 1
fi

# validate the caddy config
cd "$caddyfile_config_dir" || exit 1
caddy validate

# reload caddy
sudo caddy reload
