#!/bin/sh

if [ "$1" = "--help" ]; then
	echo "Outputs template whose output can be piped to an environment file.

This script is typically run by the 'dotenv-generate' script.

Options:
  - By default, this script outputs a '.env' file.
  - To generate a '.envrc' template, pass the '--envrc' flag.
    - This prepends 'export ' to each environment variable so the resulting file can be sourced using a shell script."
	exit
fi

# parse args
while test $# -gt 0; do
	case "$1" in
	--envrc)
		# generate a '.envrc' style template instead of a '.env'
		is_envrc=1
		;;
	esac
	shift
done

echo "# phoenix
${is_envrc:+"export "}PHX_HOST=\"${PHX_HOST:-phoenix-todo-list.localhost}\"
${is_envrc:+"export "}PORT=\"${PORT:-4000}\"
${is_envrc:+"export "}SECRET_KEY_BASE=\"${SECRET_KEY_BASE:-$(openssl rand -base64 48)}\"

# db
${is_envrc:+"export "}POSTGRES_DB=\"${POSTGRES_DB:-todo_list}\"
${is_envrc:+"export "}POSTGRES_USER=\"${POSTGRES_USER:-postgres}\"
${is_envrc:+"export "}POSTGRES_PASSWORD=\"${POSTGRES_PASSWORD:-postgres}\"
${is_envrc:+"export "}DATABASE_URL=\"${DATABASE_URL:-ecto://postgres:postgres@localhost/todo_list}\"

# traefik
TRAEFIK_HOST=\"${TRAEFIK_HOST:-localhost}\"

# # email
# ${is_envrc:+"export "}AWS_REGION=\"${AWS_REGION:-us-east-1}\"
# ${is_envrc:+"export "}AWS_ACCESS_KEY=\"${AWS_ACCESS_KEY:-your_aws_access_key}\"
# ${is_envrc:+"export "}AWS_SECRET=\"${AWS_SECRET:-your_aws_secret}\""
