#!/bin/bash

if [ "$1" = "--help" ]; then
	echo "Prints a dotenv template whose output can be piped to a '.env' file."
	exit 0
fi

echo "# phoenix
PHX_HOST=\"${PHX_HOST:-phoenix-todo-list.localhost}\"
PORT=\"${PORT:-4000}\"
SECRET_KEY_BASE=\"${SECRET_KEY_BASE:-$(openssl rand -base64 48)}\"

# db
POSTGRES_DB=\"${POSTGRES_DB:-todo_list}\"
POSTGRES_USER=\"${POSTGRES_USER:-postgres}\"
POSTGRES_PASSWORD=\"${POSTGRES_PASSWORD:-postgres}\"
DATABASE_URL=\"${DATABASE_URL:-ecto://postgres:postgres@localhost/todo_list}\"

# traefik
TRAEFIK_HOST=\"${TRAEFIK_HOST:-localhost}\"

# # email
# AWS_REGION=\"${AWS_REGION:-us-east-1}\"
# AWS_ACCESS_KEY=\"${AWS_ACCESS_KEY:-your_aws_access_key}\"
# AWS_SECRET=\"${AWS_SECRET:-your_aws_secret}\""
