#!/bin/sh

if [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
  echo "Create a new Phoenix release."
  exit
fi

# navigate to project root directory
cd "$(dirname "$0")/../../" || exit 1

# fetch and compile dependencies
echo "Fetching and compiling dependencies..."
mix deps.get --only prod
MIX_ENV=prod mix compile

# compile assets
echo "Compiling assets..."
MIX_ENV=prod mix assets.deploy

# create release
echo "Creating release..."
mix phx.gen.release "$@"
MIX_ENV=prod mix release

echo "done"
