#!/bin/bash

if [ "$1" = "--help" ]; then
	echo "Prints a '.envrc' template whose output can be piped to a '.envrc' file."
	exit 0
fi

echo "# phoenix
export PHX_HOST=\"${PHX_HOST:-phoenix-todo-list.localhost}\"
export PORT=\"${PORT:-4000}\"
export SECRET_KEY_BASE=\"${SECRET_KEY_BASE:-$(openssl rand -base64 48)}\"

# db
export POSTGRES_DB=\"${POSTGRES_DB:-todo_list}\"
export POSTGRES_USER=\"${POSTGRES_USER:-postgres}\"
export POSTGRES_PASSWORD=\"${POSTGRES_PASSWORD:-postgres}\"
export DATABASE_URL=\"${DATABASE_URL:-ecto://postgres:postgres@localhost/todo_list}\"

# traefik
export TRAEFIK_HOST=\"${TRAEFIK_HOST:-localhost}\"

# # email
# export AWS_REGION=\"${AWS_REGION:-us-east-1}\"
# export AWS_ACCESS_KEY=\"${AWS_ACCESS_KEY:-your_aws_access_key}\"
# export AWS_SECRET=\"${AWS_SECRET:-your_aws_secret}\""
