#!/bin/sh

if [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
  echo "This script runs a load test using 'wrk'. 'wrk' must be installed for this script to work.

Run this script with no parameters to run a basic load test:
  - e.g. 'loadtest-wrk'

Pass the WRK_URL environment variable to test a specific URL:
  - e.g. 'WRK_URL=https://your-project.localhost/ loadtest-wrk'

Use positional arguments to run a custom 'wrk' command. The \$URL will automatically be appended to the end of the command:
  - e.g. 'loadtest-wrk -t12 -c400 -d30s \$URL'"
  exit
fi

WRK_URL=${WRK_URL:-"https://${PHX_HOST:?}"}

if [ "$1" = "" ]; then
  # if no args passed, run a basic test
  echo "\033[96mRunning a basic load test on URL '$WRK_URL'...\033[39m"
  wrk -t12 -c400 -d10s "$WRK_URL"
else
  # run a custom test
  echo "\033[96mRunning a custom load test on URL '$WRK_URL'...\033[39m"
  # shellcheck disable=SC2068
  wrk $@ "$WRK_URL"
fi
