#!/bin/sh

if [ "$1" = "--help" ]; then
  echo "This script creates a new Phoenix release."
  exit 0
fi

# navigate to project root directory
cd $(dirname "$0")/../../

# environment variables
if [ "$SECRET_KEY_BASE" = "" ]; then
  echo "SECRET_KEY_BASE environment variable not set. Aborting..."
  exit 1
elif [ "$DATABASE_PATH" = "" ]; then
  echo "DATABASE_PATH environment variable not set. Aborting..."
  exit 1
fi

# fetch and compile dependencies
echo "Fetching and compiling dependencies..."
mix deps.get --only prod
MIX_ENV=prod mix compile

# compile assets
echo "Compiling assets..."
MIX_ENV=PROD mix assets.deploy

# create release
echo "Creating release..."
mix phx.gen.release "$@"
mix release

echo "done"
