#!/bin/sh

if [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
  echo "Run migrations and start the prod server."
  exit
fi

project_name="todo_list"
current_script_directory="$(dirname "$0")"
project_root_directory="$(cd "${current_script_directory}/../.." && pwd)"
working_directory="${project_root_directory}/_build/prod/rel/${project_name}/bin"

# navigate to working directory
cd "$working_directory" || exit 1

# run migrations
echo "Running migrations..."
./migrate

# start the server
echo "Starting the prod server..."
./server
