#!/bin/sh

if [ "$1" = "--help" ]; then
  echo "This script spawns an iEX shell."
  exit 0
fi

# navigate to project root directory
cd $(dirname "$0")/../../

# set MIX_ENV (defaults to 'test' so that 'recompile()' will work, otherwise
# credo may cause issues with recompiling)
if [ "$1" != "" ]; then
  MIX_ENV="$1"
elif [ "$MIX_ENV" = "" ]; then
  MIX_ENV="test"
fi

echo "Spawning iex shell using the '$MIX_ENV' environment..."

if [ "$MIX_ENV" = "test" ]; then
  echo -e "Note: Because you are using the 'test' environment, the 'recompile()' function should work as expected.\n"
else
  echo -e "Note: For the 'recompile()' function to work, you may need to use the 'test' environment (because of credo).\n"
fi

# use test environment so `recompile()` works
iex -S mix
