#!/bin/sh

if [ "$1" = "--help" ]; then
  echo "Start a Phoenix server in the 'dev' environment with an iEX shell."
  exit 0
fi

# navigate to project root directory
cd $(dirname "$0")/../../

# start the server
MIX_ENV=$MIX_ENV iex -S mix phx.server
