#!/bin/sh

service_name="phoenix-todo-list"

if [ "$1" = "--help" ]; then
  echo "Show the logs for this project's 'systemd' service."
  exit 0
fi

# -e - jump to the [e]nd of the pager
# -f - [f]ollow the logs
# -x - add e[x]planatory lines
# -u - monitor a specific [u]nit file (must be positioned last)

# journalctl --user -efx --unit $service_name
journalctl --user -efxu $service_name
