#!/bin/sh

service_name="phoenix-todo-list"

if [ "$1" = "--help" ]; then
  echo "This script bootstraps this project's user-level systemd service file.

It does the following:
- Runs the user-level systemd service file generator (for containers)
- Reloads the user-level systemd daemons
- Enables the service on startup
  - NOTE: Lingering must be enabled by the superuser: 'sudo loginctl enable-linger $USER'
- Starts the service"
  exit 0
fi

# navigate to current directory
cd "$(dirname "$0")" || exit 1

# run the systemd service file generator script
./systemd-container-service-file-generate "$@"

# reload the systemd daemons
systemctl --user daemon-reload

# enable the service on startup
systemctl --user enable $service_name.service

# (re)start the service
systemctl --user restart $service_name.service
