#!/bin/sh

if [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
  echo "Run this project's Javascript unit tests in watch mode."
  exit
fi

# navigate to the project's npm root directory
cd "$(dirname "$0")/../../assets" || exit 1

# run the tests
npm run test-unit-watch
