#!/bin/sh

if [ "$1" = "--help" ]; then
  echo "Run Playwright end-to-end tests in watch mode."
  exit 0
fi

# navigate to project root directory
cd "$(dirname "$0")/../../" || exit 1

# watch the test files and re-run when any of the files are modified
until ag -g "test/js/.*\.(js|ts)$" | entr -d ./support/scripts/test-e2e "$@"; do sleep 1; done
