#!/bin/sh

if [ "$1" = "--help" ]; then
  echo "Run this project's Javascript unit tests (Powered by Vitest)."
  exit 0
fi

# navigate to JS test root directory
cd $(dirname "$0")/../../test/js/

# run the tests
npm run unit
