#!/bin/sh

if [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
  echo "Run a batch of end-to-end tests (powered by Playwright)."
  exit
fi

# navigate to project root directory
cd "$(dirname "$0")/../.." || exit 1

# get reference to project root directory
project_root_directory=$(pwd)

# navigate to the project's npm root directory
cd assets || exit 1

# run the tests
npx playwright test "$@"

# remember return code from test results
test_return_code="$?"

# reset the database after E2E tests
cd "$project_root_directory" || exit 1
echo "\033[96mE2E tests complete. Resetting the test database...\033[39m"
result=$(MIX_ENV="test" mix ecto.reset >/dev/null)

# show success message after resetting the test database
if [ "$result" = 0 ]; then
  echo "\033[96m" "Test database reset successfully." "\033[39m"
fi

# pass the return code to the shell (or any parent scripts)
exit $test_return_code
