#!/bin/sh

if [ "$1" = "--help" ]; then
  echo "This script runs this project's Javascript unit tests in watch mode."
  exit 0
fi

# navigate to JS test root directory
cd $(dirname "$0")/../../test/js/

# run the tests
npm run unit-watch
