#!/bin/sh

if [ "$1" = "--help" ]; then
  echo "This script runs Playwright end-to-end tests in watch mode."
  exit 0
fi

# navigate to project root directory
cd $(dirname "$0")/../../

# find all JS test files that aren't in exempted directories, and run the tests
# when any change is detected in the files
while sleep 1; do
  find $app_dir -name '*.spec.ts' -o -name '*.spec.js' -not -path '*/node_modules/*' | entr ./support/scripts/test-e2e "$@"
done
