#!/bin/bash

show_help() {
  echo "This script creates a pg_dump backup. It must be run outside the container.

The backup file will be created in the same directory as this script. It will be created with a timestamp in the filename.
  - e.g. 'phoenix-todo-list--pg-dump-2022-11-05-06-23-37.dump'

This script takes no arguments."
}

if [ "$1" = "--help" ]; then
  show_help
  exit
fi

podman exec -it phoenix-todo-list--postgres /var/lib/postgresql/backups/backup-create-inside-container
