#!/bin/sh

# shellcheck disable=SC2153

show_help() {
  echo "This script creates a pg_dump backup. It must be run outside the container.

The backup file will be created in the same directory as this script. It will be created with a timestamp in the filename.
  - e.g. 'phoenix-todo-list--pg-dump-2022-11-05-06-23-37.dump'

This script accepts the following environment variable(s):
  - POSTGRES_CONTAINER_NAME: The name of the Postgres container to be backed up
    - Default: 'phoenix-todo-list_postgres'

To use Podman instead of Docker, pass '--podman' as the last positional argument."
}

if [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
  show_help
  exit
fi

# configure postgres container name
if [ "$POSTGRES_CONTAINER_NAME" != "" ]; then
  postgres_container_name="$POSTGRES_CONTAINER_NAME"
else
  postgres_container_name="phoenix-todo-list-postgres-1"
fi

# configure container manager
if [ "$1" = "--podman" ]; then
  container_manager=podman
else
  container_manager=docker
fi

echo "Creating backup in Postgres container volume directory '/var/lib/postgresql/backups/'..."

$container_manager exec -it "$postgres_container_name" /var/lib/postgresql/backups/backup-create-inside-container
