#!/bin/sh

if [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
  echo "This script runs a Grafana container.

Features:
  - Runs with host networking
  - Accessible via port 3000
  - Uses Docker by default.
    - Use Podman by passing either of the '-p' or '--podman' flags."
fi

container_runtime=docker
if [ "$1" = "-p" ] || [ "$1" = "--podman" ]; then
  container_runtime=podman
fi

echo "Starting a Grafana container with host networking on port 3000 with username 'admin' and password 'admin'...
To stop and remove this container, run '$container_runtime stop grafana'."

$container_runtime run -d --rm --name=grafana --network=host docker.io/grafana/grafana
