#!/bin/sh

if [ "$1" = "--help" ]; then
  echo "This script removes root permissions on any Docker volumes created in 'support/containers/volumes'.

It uses 'chown' to change ownership of the volume directory to the current user."
  exit 1
fi

# navigate to container volumes directory
cd "$(dirname "$0")/../volumes/" || exit 1

echo "Fixing user permissions on container volumes..."

# shellcheck disable=SC2086
if ! chown -R $USER:$USER .; then
  echo "\033[96mPermission denied. Trying again as superuser...\033[39m"
  if sudo chown -R $USER:$USER .; then
    echo "\033[92mok\033[39m"
  fi
fi
