#!/bin/sh

# change to project root directory
cd $(dirname "$0")/../

# set MIX_ENV
if [ "$1" != "" ]; then
  MIX_ENV="$1"
elif [ "$MIX_ENV" = "" ]; then
  MIX_ENV="dev"
fi

echo "Starting Phoenix server using the '$MIX_ENV' environment...
"

iex -S mix phx.server
