#!/bin/sh

# get project root directory
cd $(dirname "$0")/../
project_root=$(pwd)

# navigate to JS test root
cd ./test/js/

npx playwright test "$@"

# reset the database after E2E tests
cd $project_root
echo "E2E tests complete. Resetting the database..."
MIX_ENV=test mix ecto.reset > /dev/null
