#!/bin/sh

# get project root directory
cd $(dirname "$0")/../
project_root=$(pwd)
# navigate to JS test root
cd ./test/js/

# run the tests
npx playwright test "$@"

# use test results for return code
test_return_code="$?"

# reset the database after E2E tests
cd $project_root
echo "\033[96m" "E2E tests complete. Resetting the test database..." "\033[39m"
MIX_ENV=test mix ecto.reset > /dev/null

if [ "$?" = 0 ]; then
  echo "\033[96m" "Test database reset successfully." "\033[39m"
fi

exit $test_return_code
