---
services:
  grafana:
    image: "docker.io/grafana/grafana:9.5.2"
    container_name: "grafana"
    restart: "always"
    network_mode: "host"
    volumes:
      - "phoenix-todo-list--grafana:/var/lib/grafana"

volumes:
  phoenix-todo-list--grafana:
    external: true
