---
services:
  postgres:
    image: "docker.io/postgres:15"
    container_name: "phoenix-todo-list-postgres"
    hostname: "postgres"
    restart: "always"
    environment:
      POSTGRES_DB: "todo_list"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    volumes:
      - "./volumes/postgres:/var/lib/postgresql/data"
  phoenix:
    depends_on:
      - "postgres"
