---
services:
  traefik:
    volumes:
      - "./etc/dev:/etc/traefik"
    labels:
      - "traefik.http.routers.traefik.entrypoints=web"

      # # require authentication to access the dashboard (uncomment the next lines to enable)
      # - "traefik.http.routers.traefik.middlewares=auth"
      #
      # # use `mkpasswd --method=bcrypt` to convert your password to a bcrypt
      # # hash before pasting it here. (make sure to double up any dollar sign
      # # symbols ($ -> $$) since the dollar sign symbol is used as an escape
      # # character in YAML)
      # - "traefik.http.middlewares.auth.basicauth.users=${TRAEFIK_DASHBOARD_CREDENTIALS:-admin:$2b$05$ziXkIFQh5zJHZYsmX1LGluwyTYx4UVT2hz/CkEsjbuxG8kdXTfuUm}"
